require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Api::V1::OutagesController do

  # This should return the minimal set of attributes required to create a valid
  # Api::V1::Outage. As you add validations to Api::V1::Outage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::OutagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all outages as @outages" do
      outage = Api::V1::Outage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:outages).should eq([outage])
    end
  end

  describe "GET show" do
    it "assigns the requested outage as @outage" do
      outage = Api::V1::Outage.create! valid_attributes
      get :show, {:id => outage.to_param}, valid_session
      assigns(:outage).should eq(outage)
    end
  end

  describe "GET new" do
    it "assigns a new outage as @outage" do
      get :new, {}, valid_session
      assigns(:outage).should be_a_new(Api::V1::Outage)
    end
  end

  describe "GET edit" do
    it "assigns the requested outage as @outage" do
      outage = Api::V1::Outage.create! valid_attributes
      get :edit, {:id => outage.to_param}, valid_session
      assigns(:outage).should eq(outage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      before(:each) do 
        @account = FactoryGirl.create(:account, :outgoing_message_format => "ooops {{title}}")
      end
      
      it "creates a new Api::V1::Outage" do
        expect {
          post :create, {:outage => valid_attributes}, valid_session
        }.to change(Api::V1::Outage, :count).by(1)
      end

      it "assigns a newly created outage as @outage" do
        post :create, {:outage => valid_attributes}, valid_session
        assigns(:outage).should be_a(Api::V1::Outage)
        assigns(:outage).should be_persisted
      end

      it "redirects to the created outage" do
        post :create, {:outage => valid_attributes}, valid_session
        response.should redirect_to(Api::V1::Outage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved outage as @outage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Outage.any_instance.stub(:save).and_return(false)
        post :create, {:outage => {}}, valid_session
        assigns(:outage).should be_a_new(Api::V1::Outage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Outage.any_instance.stub(:save).and_return(false)
        post :create, {:outage => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      before(:each) do 
        @account = FactoryGirl.create(:account, :outgoing_message_format => "ooops {{title}}")
      end
      
      it "updates the requested outage" do
        outage = Api::V1::Outage.create! valid_attributes
        # Assuming there are no other outages in the database, this
        # specifies that the Api::V1::Outage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Api::V1::Outage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => outage.to_param, :outage => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested outage as @outage" do
        outage = Api::V1::Outage.create! valid_attributes
        put :update, {:id => outage.to_param, :outage => valid_attributes}, valid_session
        assigns(:outage).should eq(outage)
      end

      it "redirects to the outage" do
        outage = Api::V1::Outage.create! valid_attributes
        put :update, {:id => outage.to_param, :outage => valid_attributes}, valid_session
        response.should redirect_to(outage)
      end
    end

    describe "with invalid params" do
      it "assigns the outage as @outage" do
        outage = Api::V1::Outage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Outage.any_instance.stub(:save).and_return(false)
        put :update, {:id => outage.to_param, :outage => {}}, valid_session
        assigns(:outage).should eq(outage)
      end

      it "re-renders the 'edit' template" do
        outage = Api::V1::Outage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::V1::Outage.any_instance.stub(:save).and_return(false)
        put :update, {:id => outage.to_param, :outage => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested outage" do
      outage = Api::V1::Outage.create! valid_attributes
      expect {
        delete :destroy, {:id => outage.to_param}, valid_session
      }.to change(Api::V1::Outage, :count).by(-1)
    end

    it "redirects to the outages list" do
      outage = Api::V1::Outage.create! valid_attributes
      delete :destroy, {:id => outage.to_param}, valid_session
      response.should redirect_to(api_v1_outages_url)
    end
  end

end
